import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    avtorization:{
        width:'100%',
        marginTop:45,
        paddingBottom:35
    },
    navWrap:{
        width:'100%',
        height:'100%',
        position:'absolute',
        top:0,
        left:0,
        backgroundColor:'rgba(0,0,0,.5)',
        zIndex:99,
    },
    activeShadow:{
        opacity:1,
        left:0
    },
    navActive:{
        left:0,
    },
    nav:{
        width:220,
        height:'100%',
        backgroundColor:'#181818',
        zIndex:110,
        paddingLeft:15,
        paddingRight:15,
    },
    ul:{
        padding:0
    },
    li:{
        paddingBottom:'1px',
        overflow:'hidden',
        marginBottom:21,
    },
    iconWrap:{
       width:24,
       marginRight:20
    },
    icon:{
        display:'block',
        margin:'auto'
    },
    liText:{
        fontSize:14,
        color:'#ffffff',
        marginTop:0,
        marginBottom:0
    },
    navLogo:{
        width:70,
        display:'block',
        margin:'auto',
        position:'absolute',
        bottom:40,
        left:0,
        right:0
    }
})