import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    text1:{
        fontSize:15,
        color:'#ffffff',
        padding:15,
        lineHeight:24
    },
    titleText:{
        fontSize:19,
        color:'#fff',
        textAlign:'right'
    },
    title:{
        backgroundColor:'#e74b3b',
        paddingRight:15,
        paddingTop:5,
        paddingBottom:5,
        paddingLeft:30,
        marginLeft:-15
    },
    text2:{
        fontSize:12,
        color:'#ffffff',
        padding:15,
        lineHeight:21
    },
    text3:{
        color:'#ffffff',
        fontSize:12,
        fontStyle:'italic',
        padding:15,
        lineHeight:21,
        marginTop:-15
    },
    podtitle:{
        color:'#ffffff',
        fontSize:12,
        fontWeight:'bold',
        padding:15,
        paddingTop:0,
        paddingBottom:0
    },
    list:{
        color:'#ffffff',
        fontSize:12,
        marginBottom:5
    },
    bottom:{
        width: '100%',
        marginLeft:-15,
        borderTopWidth:1,
        borderColor:'#2f2f2f',
        padding:15
    },
    bottomText:{
        fontSize:15,
        color:'#ffffff',
        margin:0,
        padding:15,
        paddingTop:0
    },
    bottomSpan:{
        color:'#e74b3b'
    },
    ul:{
        padding:15,
        paddingLeft:35
    }
})