import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    itemCol:{
        maxWidth:'50%',
        width:'50%',
        height:120,
        padding:2.5,
        position:'relative',
        backgroundColor:'rgba(0,0,0,0)',
        marginBottom:15
    },
    catalogRow:{
        width:'100%',
        flexDirection:'row',
        flexWrap:'wrap',
        flexGrow:2,
        marginLeft:-2.5,
        marginRight:-2.5,
        paddingBottom:40
    },
    itemBlock:{
        width:'100%',
        height:120,
    },
    catalogBlock:{
        paddingTop:15,
        paddingBottom:60
    },
    icon:{
        position:'absolute',
        width:'100%',
        height:'100%',
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        flexDirection:'row',
        alignItems:'center',
    },
    iconWrap:{
        display:'flex',
        alignItems:'center',
        alignSelf:'center',
    },
    iconImg:{
        margin:'auto'
    },
    iconText:{
        color:'#fff',
        fontSize:12,
        margin:0,
        marginTop:10,
        minWidth:63,
        textAlign:'center',
        backgroundColor:'rgba(0,0,0,0)',
        width:50
    },
    item:{
        width:'100%',
        padding:15,
        position:'relative',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'flex-start',
        flexDirection:'row',
        borderBottomWidth:1,
        borderColor:'rgba(255,255,255,.1)'
    },
    itemPich:{
        flex:1,
        maxWidth:85,
        height:85,
        position:'relative'
    },
    itemText:{
        flex:1,
        paddingLeft:15
    },
    itemImgWr:{
        width:85,
        height:85,
        position:'relative'
    },
    img:{
        width:85,
        height:85,
        position:'absolute',
        top:0,
        left:0
    },
    name:{
        fontSize:16,
        color:'#ffffff',
        marginTop:0,
        marginBottom:5,
        lineHeight:16,
        width:'100%',
        overflow: 'hidden'
    },
    descroption:{
        fontSize:12,
        color:'#ffffff',
        marginTop:0,
        overflow: 'hidden',
        lineHeight:12,
        maxHeight:40
    },
    num:{
        width:81,
        height:24,
        backgroundColor:'#d34536',
        borderRadius:5,
    },
    plus:{
        width:25,
        height:24,
        borderColor:'#fff',
        borderLeftWidth:1,
        fontSize:25,
        textAlign:'center',
        color:'#ffffff',
        lineHeight:21,
    },
    price:{
        width:56,
        height:24,
        textAlign:'center',
        color:'#ffffff',
        fontSize:15,
        lineHeight:22
    },
    statusItem:{
        width:23,
        height:23,
        borderRadius:23,
        fontSize:9,
        color:'#ffffff',
        lineHeight:23,
        textAlign:'center',
        marginBottom:3
    },
    newIt:{
        backgroundColor:'#119229'
    },
    hitIt:{
        backgroundColor:'#e80057'
    },
    it15:{
        backgroundColor:'#e99821'
    },
    categoryWr:{
        paddingBottom:80
    },
    start:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row'
    },
    width:{
        width:113,
        height:24,
        overflow:'hidden',
        borderColor:'#e74b3b',
        borderWidth:1,
        borderRadius:5,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    buttons:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row',
        marginTop:13
    },
    widthItem:{
        width:'50%',
        height:22,
        overflow:'hidden',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    widthText:{
        fontSize:13,
        textAlign:'center',
        color:'#ffffff',
        lineHeight:17,
    },
    widthItemActive:{
        backgroundColor:'#dc4738',
        borderRadius:4
    },
    numItem:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        width:81,
        height:24,
        borderWidth: 1,
        borderColor: '#e64b3b',
        marginTop:0
    },
    uiNumM:{
        flex:1,
        backgroundColor:'#e64b3b',
        maxWidth:24,
        height:22,
        marginTop:0
    },
    input:{
        flex:1,
        fontSize:14,
        backgroundColor:'rgba(0,0,0,0)',
        maxWidth:31,
        height:22,
        color:'#fff',
        textAlign:'center'
    },
    minus:{
        fontSize:35,
        textAlign:'center',
        color:'#ffffff',
        lineHeight:21,
    },
    bottom:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        paddingTop:11,
        paddingLeft:15,
        paddingRight:15
    },
    col:{
        display:'flex',
        flexWrap: 'wrap',
        alignItems:'center',
        flexDirection:'row',
        flex:1,
        height:41
    },
    colLeft:{
        justifyContent:'flex-start',
    },
    colRight:{
        justifyContent:'flex-end',
    },
    bottomPanel:{
        width:'100%',
        height:63,
        position:'relative'
    },
    bottomBg:{
        width:'100%', 
        height:63,
        position:'absolute', 
        top:0,
        bottom:0,
        left:0,
        right:0
    },
    iconKorz:{
        marginLeft:15
    },
    bottomTextOne:{
        color:'#ffffff',
        fontSize:11,
    },
    bottomTextTwo:{
        color:'#ffffff',
        fontSize:11,
        marginTop:0,
        marginBottom:0,
        lineHeight:21,
    },
    bottomTextTwoSpan:{
        fontSize:21,
        fontWeight:'bold'
    },
    textRight:{
        textAlign:'right'
    },
    border:{
        borderLeftWidth:1,
        borderColor:'#ab2e20'
    },
    nextOrder:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        height:64
    }
})