import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    itemCol:{
        maxWidth:'50%',
        width:'50%',
        padding:2.5,
    },
    blockImage:{
        width:'100%'
    },
    catalogRow:{
        width:'100%',
        flexDirection:'row',
        flexWrap:'wrap',
        flexGrow:2,
        marginLeft:-2.5,
        marginRight:-2.5,
        paddingBottom:40
    },
    itemBlock:{
        width:'100%',
        height:120,
        borderRadius:5,
        overflow:'hidden',
        position:'relative'
    },
    catalogBlock:{
        paddingTop:15,
        paddingBottom:60
    },
    icon:{
        position:'absolute',
        width:'100%',
        height:'100%',
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        flexDirection:'row',
        alignItems:'center',
    },
    iconWrap:{
        display:'flex',
        alignItems:'center',
        alignSelf:'center',
    },
    iconImg:{
        margin:'auto'
    },
    iconText:{
        color:'#fff',
        fontSize:12,
        margin:0,
        marginTop:10,
        minWidth:63,
        textAlign:'center',
        backgroundColor:'rgba(0,0,0,0)',
        width:50
    },
    item:{
        width:'100%',
        padding:15,
        position:'relative',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'flex-start',
        flexDirection:'row'
    },
    itemPich:{
        flex:1,
        maxWidth:85,
        height:85,
        position:'relative'
    },
    itemText:{
        flex:1,
        paddingLeft:15
    },
    itemImgWr:{
        width:85,
        height:85,
        overflow:'hidden',
        position:'relative'
    },
    img:{
        width:85,
        height:85
    },
    name:{
        fontSize:16,
        color:'#ffffff',
        marginTop:0,
        marginBottom:5,
        lineHeight:16,
        width:'100%',
        overflow: 'hidden'
    },
    descroption:{
        fontSize:12,
        color:'#ffffff',
        marginTop:0,
        overflow: 'hidden',
        lineHeight:12,
        maxHeight:40
    },
    num:{
        width:81,
        height:24,
        backgroundColor:'#d34536',
        borderRadius:5,
    },
    plus:{
        width:25,
        height:24,
        borderColor:'#fff',
        borderLeftWidth:1,
        fontSize:25,
        textAlign:'center',
        color:'#ffffff',
        lineHeight:21,
    },
    price:{
        width:56,
        height:24,
        textAlign:'center',
        color:'#ffffff',
        fontSize:15,
        lineHeight:22
    },
    statusItem:{
        width:23,
        height:23,
        borderRadius:23,
        fontSize:9,
        color:'#ffffff',
        lineHeight:23,
        textAlign:'center',
        marginBottom:3
    },
    newIt:{
        backgroundColor:'#119229'
    },
    hitIt:{
        backgroundColor:'#e80057'
    },
    it15:{
        backgroundColor:'#e99821'
    },
    categoryWr:{
        paddingBottom:80
    },
    start:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row'
    },
    width:{
        width:113,
        height:24,
        overflow:'hidden',
        borderColor:'#e74b3b',
        borderWidth:1,
        borderRadius:5,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    buttons:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row',
        marginTop:13
    },
    widthItem:{
        width:'50%',
        height:22,
        overflow:'hidden',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    widthText:{
        fontSize:13,
        textAlign:'center',
        color:'#ffffff',
        lineHeight:17,
    },
    widthItemActive:{
        backgroundColor:'#dc4738',
        borderRadius:4
    },
})