import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    basketPage:{
        marginLeft:-15,
        marginRight:-15,
        overflow:'hidden',
        marginTop:-15
    },
    basketAvtorizations:{
        width:'100%',
        height:65,
        overflow:'hidden',
        paddingLeft:15,
        paddingRight:15,
    },
    avtorizationsText:{
        fontSize:16,
        color:'#e74b3b',
        marginTop:10
    },
    avtorizationSpan:{
        color:'#ffffff',
        fontSize:11,
    },
    code:{
        width:'100%',
        height:70,
        paddingLeft:25,
        paddingRight:25,
        backgroundColor:'rgba(44,44,44,.7)'
    },
    codeInput:{
        width:'100%',
        height:35,
        backgroundColor:'rgba(0,0,0,0)',
        borderBottomWidth:1,
        borderColor:'#585b60',
        marginTop:15,
        fontSize:15,
    },
    items:{
        width:'100%',
    },
    item:{
        width:'100%',
        padding:15,
        overflow:'hidden',
        borderBottomWidth:1,
        borderColor:'#3e3e3e',
    },
    itemTop:{
        width:'100%',
        overflow:'hidden',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'flex-start',
        flexDirection:'row',
        paddingLeft:15,
    },
    itemTopLeft:{
        width:'70%',
        overflow:'hidden'
    },
    itemTopRight:{
        width:'30%',
        overflow:'hidden'
    },
    type:{
        color:'#ffffff',
        fontSize:11,
        marginTop:0,
        marginBottom:0
    },
    name:{
        fontSize:15,
        color:'#ffffff',
        marginTop:5
    },
    uiNum:{
        width:'100%',
        marginTop:5
    },
    list:{
        width:'100%',
        overflow:'hidden'
    },
    listItem:{
        paddingTop:5,
        paddingLeft:15,
        paddingRight:15,
        paddingBottom:5,
        fontSize:12,
        color:'#ffffff',
        backgroundColor:'rgba(44,44,44,.4)',
        marginRight:5,
        borderRadius:5
    },
    summ:{
        fontSize:16,
        color:'#ffffff',
        marginBottom:0,
        paddingLeft:15,
        paddingTop:15
    },
    total:{
        width:'100%',
        paddingLeft:15,
        paddingRight:30,
        overflow:'hidden',
        paddingTop:20
    },
    totalTextOne:{
        color:'#ffffff',
        fontSize:14,
        textAlign:'right',
        marginBottom:0
    },
    totalSpan:{
        fontSize:21,
    },
    totalTextTwo:{
        textAlign:'right',
        color:'#ffffff',
        fontSize:12,
        marginTop:0
    }
})