import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    detailPage:{
        marginTop:0
    },
    detailPich:{
        width:'100%',
        height:200
    },
    detailImg:{
        width:'100%',
        height:200
    },
    detailText:{
        position:'relative',
        width:'100%',
        zIndex:1,
        padding:15
    },
    itemStatus:{
        width:29,
        height:29,
        borderRadius:29,
        fontSize:11,
        color:'#fff',
        lineHeight:29,
        textAlign:'center',
        marginRight:10
    },
    imgIcon:{
        width:14,
        height:14,
    },
    detailTextStatus:{
        width:'100%',
        overflow:'hidden',
        marginTop:-15
    },
    name:{
        fontSize:24,
        color:'#fff',
        marginTop:10,
        marginBottom:10
    },
    description:{
        color:'#ffffff',
        fontSize:13,
    },
    span:{
        fontSize:11,
        marginBottom:10
    },
    list:{
        width:'100%',
        overflow:'hidden',
        paddingTop:15,
        paddingLeft:15,
        paddingRight:15
    },
    listItem:{
        width:'100%',
        height:60,
        backgroundColor:'#2c2c2c',
        overflow:'hidden',
        borderLeftWidth:3,
        borderColor:'#df4839',
        marginBottom:5,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row',
        paddingRight:15
    },
    listItemLeft:{
        maxWidth:60,
    },
    listItemRight:{
        width:'40%',
        height:60,
    },
    param:{
        fontSize:11,
        color:'#ffffff',
        textAlign:'center',
        lineHeight:16,
        width:64
    },
    paramNum:{
        fontSize:17
    },
    price:{
        fontSize:24,
        color:'#ffffff',
        paddingLeft:15,
        paddingRight:15
    },
    addIngredient:{
        width:'100%',
        height:50,
        borderRadius:4,
        borderWidth:1,
        borderColor:'#fff',
        marginTop:20,
        marginBottom:20
    },
    addIngredientText:{
        textAlign:'center',
        color:'#ffffff',
        fontSize:14,
        lineHeight:48,
        margin:0
    },
    addIngredientImg:{
        width:14,
        marginRight:15
    },
    recomendation:{
        marginLeft:-15,
        marginRight:-15
    },
    col:{
        flex:1
    },
    recomendationTitle:{
        width:'100%',
        height:30,
        backgroundColor:'#2c2c2c',
        overflow:'hidden',
        lineHeight:30,
        paddingLeft:15,
        paddingRight:15,
        color:'#ffffff',
        fontSize:13
    },
    uiNum:{
        borderWidth:0,
        borderRadius:5,
        overflow:'hidden',
    },
    addCartText:{
        color:'#fff',
        textAlign:'center',
        fontSize:14,
        fontWeight:'bold',
        lineHeight:23
    },
    numItem:{
        width: 125,
        height: 30,
        marginTop:15
    },
    uiNumM:{
        flex:1,
        backgroundColor:'#e64b3b',
        height:30
    },
    input:{
        maxWidth:50
    }
})