import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    blockCard:{
        height:200,
        position:'relative',
        marginTop:15
    },
    cardContent:{
        position:'relative',
        width:'100%',
        height:'100%',
        minHeight:208,
        zIndex:2
    },
    cardTop:{
        width:'100%',
        paddingRight:15,
        paddingTop:15,
    },
    cardLogo:{
        width:'40%',
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        flexDirection:'row',
        alignItems:'center',
    },
    cardLogoImg:{
        width:75,
        height:56,
    },
    cardlogoNum:{
        fontSize:10,
        color:'#fff',
        textAlign:'center',
        backgroundColor:'rgba(0,0,0,0)',
        marginTop:5
    },
    cardInfo:{
        width:'60%',
        backgroundColor:'rgba(0,0,0,0)'
    },
    cardNameText:{
        fontSize:16,
        color:'#fff',
        marginTop:-2,
        backgroundColor:'rgba(0,0,0,0)'
    },
    cardScore:{
        fontSize:11,
        color:'#fff',
        backgroundColor:'rgba(0,0,0,0)'
    },
    cardScoreActive:{
        fontSize:16,
        backgroundColor:'rgba(0,0,0,0)'
    },
    cardBottom:{
        width:'100%',
        height:65,
        marginTop:5,
        paddingLeft:15,
        paddingRight:15,
    },
    cardBottomLeft:{
        width:'30%',
        height:65,
        paddingTop:8
    },
    cardBottomNum:{
        fontSize:12,
        height:65,
        color:'#fff',
        backgroundColor:'rgba(0,0,0,0)'
    },
    cardBottomNumAction:{
        fontSize:32,
    },
    cardBottomRight:{
        width:'70%',
        paddingLeft:15
    },
    cardButtonWrap:{
        width:'100%',
        height:44,
        borderWidth:1,
        borderColor:'#fff',
        borderStyle:'solid',
        borderRadius:4,
        marginTop:11,
    },
    cardButton:{
        width:'50%',
        height:42,
        fontSize:8,
        color:'#fff',
        textAlign:'center',
        borderWidth:1,
        borderColor:'#ffffff',
        borderStyle:'solid',
        paddingTop:8
    },
    cardButtonOne:{
    },
    cardButtonText:{
        fontSize:11,
        textAlign:'center',
        display:'block',
        width:90,
        height:42,
        marginTop:2,
    },
    noUserText:{
        fontSize:10,
        color:'#fff',
        marginTop:4,
        marginBottom:7
    },
    noUserButton:{
        borderWidth:1,
        borderColor:'#fff',
        borderStyle:'solid',
        height:30,
        borderRadius: 5,
        width: 140,
        backgroundColor:'rgba(0,0,0,0)',
    },
    noUserButtonText:{
        textAlign: 'center',
        fontSize: 10,
        color: '#fff',
        marginTop:5,
    },
    cardProcent:{
        width:87,
        height:50
    },
    procentSpan:{
        fontSize:35,
        color:'#fff',
        textAlign:'center',
        position:'absolute',
        width:'100%',
        lineHeight: 35
    },
    procentText:{
        fontSize:10,
        color:'#fff',
        textAlign:'center',
        marginTop:6
    },
})