import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    Top:{
        paddingTop:25,
        paddingBottom:25,
        marginTop:-15
    },
    topOne:{
        margin:0,
        fontSize:14,
        color:'#ffffff',
        textAlign:'center',
        fontWeight:'bold'
    },
    topTwo:{
        margin:0,
        color:'#d94738',
        textAlign:'center',
        fontSize:27,
        fontWeight:'bold'
    },
    topThree:{
        fontSize:14,
        color:'#ffffff',
        textAlign:'center',
        marginTop:4,
        marginBottom:0
    },
    item:{
        width: '100%',
        height:100,
        backgroundColor:'#2c2c2c',
        borderLeftWidth:4,
        borderColor:'#e04939',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row'
    },
    itemLeft:{
        width:'30%',
        height:100,
        position:'relative',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    itemRight:{
        width:'70%',
        height:100,
    },
    itemLeftImg:{
        width:'75%',
        margin:'auto',
        position:'absolute',
        top:0,
        bottom:0,
        left:0,
        right:0
    },
    sity:{
        fontSize:11,
        color:'#ffffff',
        marginBottom:0,
        marginTop:12,
        fontWeight:'bold'
    },
    addres:{
        fontSize:16,
        color:'#ffffff',
        marginTop:0,
        marginBottom:5,
        fontWeight:'bold'
    },
    addMap:{
        paddingTop:5,
        paddingBottom:5,
        paddingLeft:15,
        paddingRight:15,
        borderRadius:4,
        borderWidth:1,
        width:174,
        borderColor:'#ffffff'
    },
    addMapText:{
        fontSize:13,
        color:'#ffffff',
        textAlign:'center',
        fontWeight:'bold'
    },
    itemPhone:{
        width: '100%',
        paddingLeft:15,
        paddingRight:15,
        marginLeft:-15,
        height:100,
        borderBottomWidth:1,
        borderColor:'#3c3c3c',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row'
    },
    itemPhoneLeft:{
        width:'50%',
        height:100,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'flex-start',
        alignItems:'center',
        flexDirection:'row',
        paddingLeft:15
    },
    itemPhoneRight:{
        width:'50%',
        height:100,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'flex-end',
        alignItems:'center',
        flexDirection:'row'
    },
    itemPhoneText:{
        fontSize:12,
        color:'#ffffff',
    },
    itemPhoneSpan:{
        color:'#ffffff',
        fontSize:17,
        marginTop:5,
        fontWeight:'bold'
    },
    itemPhoneButton:{
        paddingTop:5,
        paddingBottom:5,
        paddingLeft:10,
        paddingRight:10,
        backgroundColor:'#d44536',
        borderRadius:4,
        width:90,
        height:29
    },
    itemPhoneButtonColor:{
        fontSize:13,
        color:'#ffffff',
        textAlign:'center',
        fontWeight:'bold'
    },
    itemPhoneTextOne:{
        color:'#ffffff',
        fontSize:12,
        marginBottom:6,
    },
    itemPhoneTextTwo:{
        color:'#ffffff',
        fontSize:14,
        marginTop:0
    }
})