import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    wrap:{
        width:'90%',
        paddingTop:10
    },
    line:{
        width:'100%',
        height:8,
        backgroundColor:'#f89a91',
        borderRadius:8,
        borderWidth:2,
        borderColor:'#f89a91',
        borderStyle:'solid',
    },
    lineProgressWrap:{
        position:'absolute',
        width:'100%',
        top:12,
        left:2,
        height:4,
        zIndex:2
    },
    procentWrap:{
        width:'102%',
        position:'absolute',
        zIndex:2,
        marginLeft:-2
    },
    num:{
        fontSize:6,
        position:'relative',
        color:'#ffe5e2',
        width:16,
        marginTop:-6,
        height:16,
        lineHeight:16,
        textAlign:'center',
        zIndex:3,
        backgroundColor:'rgba(0,0,0,0)'
    },
    lineProgress:{
        height:4,
        backgroundColor:'#e74b3b',
        borderRadius:4,
        position:'relative',
        zIndex:1
    },
    items:{
        width:'102%',
    },
    item:{
        marginTop:-12,
    },
    circle:{
        width:16,
        height:16,
        borderRadius:16,
        backgroundColor:'#e74b3b',
        borderWidth:2,
        borderColor:'#f89a91',
        borderStyle:'solid',
        position:'relative',
        zIndex:1,
    },
    
    text:{
        fontSize:10,
        color:'#ffe5e2',
        lineHeight:10,
        marginTop:18,
        width:30,
        zIndex:3,
        backgroundColor:'rgba(0,0,0,0)',
        position:'absolute'
    },
    active:{
        
    }
})