import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    wrap:{
        width:'90%',
        position:'relative',
        paddingTop:10
    },
    line:{
        width:'100%',
        height:8,
        backgroundColor:'rgba(255,255,255,.2)',
        borderRadius:8,
    },
    lineProgressWrap:{
        position:'absolute',
        width:'100%',
        top:12,
        left:2,
        height:4,
        zIndex:2
    },
    procentWrap:{
        width:'102%',
        position:'absolute',
        zIndex:2,
        marginLeft:-2
    },
    lineProgress:{
        height:4,
        backgroundColor:'#e74b3b',
        borderRadius:4,
        position:'relative',
        zIndex:1
    },
    lin:{
        height:4,
        backgroundColor:'#e74b3b',
    },
    items:{
        width:'102%',
        display: 'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        flexDirection:'row',
        alignItems:'center',
    },
    item:{
        marginTop:-12,
        height:45,
    },
    circle:{
        width:16,
        height:16,
        borderRadius:16,
        backgroundColor:'#e74b3b',
        borderWidth:2,
        borderColor:'rgba(255,255,255,.2)',
        borderStyle:'solid',
        position:'relative',
        zIndex:1,
    },
    num:{
        fontSize:6,
        position:'relative',
        marginTop:-12,
        color:'#ffe5e2',
        width:18,
        height:18,
        textAlign:'center',
        zIndex:3,
        marginLeft:-1
    },
    text:{
        fontSize:10,
        color:'#ffe5e2',
        marginTop:17,
        position:'absolute',
        lineHeight:10,
        width:40,
        height:45
    },
    opacity:{
        opacity:.6
    }
})