import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    itemTextOne:{
        fontSize:21,
        color:'#ffffff',
        textAlign:'center',
        marginBottom:0,
        marginTop:5
    },
    itemTextTwo:{
        fontSize:11,
        color:'#ffffff',
        textAlign:'center',
        marginTop:4
    },
    itemBlock:{
        width:285,
        borderRadius:10,
        margin:'auto',
        marginTop:15,
        backgroundColor:'#222222'
    },
    it:{
        borderBottomWidth:1,
        borderColor:'#383838',
        paddingBottom:15,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'flex-start',
        flexDirection:'row',
    },
    itLeft:{
        width:'25%',
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'flex-start',
        flexDirection:'row',
        paddingTop:13
    },
    itemBlockWrap:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        paddingTop:10
    },
    itRight:{
        width:'75%',
    },
    itLeftImg:{
        width:26,
        height:26,
        
    },
    pOne:{
        fontSize:14,
        color:'#ffffff',
        marginBottom:3,
        marginTop:10,
        fontWeight:'bold'
    },
    pTwo:{
        fontSize:11,
        color:'#ffffff',
        marginTop:0,
        paddingRight:15,
        marginBottom:0
    },
    fullBlock:{
        width:'100%',
        height:73,
        marginTop:40,
        marginBottom:40,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row',
        backgroundColor:'#222222',
    },
    fullText:{
        margin:0,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    fullTextSt:{
        textAlign:'center',
        color:'#ffffff',
        fontSize:17,
    },
    fullTextImg:{
        width:16,
        height:16,
        marginRight:10
    },
    bottom:{
        width:'100%',
        marginLeft:-15,
        borderTopWidth:1,
        borderColor:'#e74b3b',
        marginTop:50
    },
    bottomTitle:{
        paddingTop:5,
        paddingBottom:5,
        paddingRight:15,
        paddingLeft:15,
        backgroundColor:'#e74b3b',
        width:162,
        height:31
    },
    bottomTitleText:{
        color:'#fff',
        fontSize:14,
        fontWeight:'bold',
        textAlign:'center'
    },
    bottomWrap:{
        width:'100%',
        overflow:'hidden',
        paddingTop:20,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'space-between',
        alignItems:'center',
        flexDirection:'row',
        paddingBottom:30
    },
    bottomItem:{
        width:'50%',
    },
    bottomItemImg:{
        
    },
    bottomItemPOne:{
        textAlign:'center',
        fontSize:14,
        color:'#e74b3b',
        marginTop:10,
        marginBottom:10
    },
    bottomItemPich:{
        height:31,
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
        flexDirection:'row'
    },
    wrapText:{
        display:'flex',
        flexWrap: 'wrap',
        justifyContent:'center',
        alignItems:'center',
    },
    bottomItemPTwo:{
        fontSize:10,
        color:'#fff',
        textAlign:'center',
        width:140,
    }
})